/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _S4_H_RPCGEN
#define _S4_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define PROGRAM 0x20000001
#define VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define getChat 1
extern  char ** getchat_1(void *, CLIENT *);
extern  char ** getchat_1_svc(void *, struct svc_req *);
#define writeMsg 2
extern  void * writemsg_1(char **, CLIENT *);
extern  void * writemsg_1_svc(char **, struct svc_req *);
extern int program_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define getChat 1
extern  char ** getchat_1();
extern  char ** getchat_1_svc();
#define writeMsg 2
extern  void * writemsg_1();
extern  void * writemsg_1_svc();
extern int program_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_S4_H_RPCGEN */
