/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "S4.h"


void
program_1(char *host)
{
	CLIENT *clnt;
	ChatLog  *result_1;
	char *getchat_1_arg;
	void  *result_2;
	char * write_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PROGRAM, VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = getchat_1((void*)&getchat_1_arg, clnt);
	if (result_1 == (ChatLog *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = write_1(&write_1_arg, clnt);
	if (result_2 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	program_1 (host);
exit (0);
}
