/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "S4.h"
#include <ncurses.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <strings.h>
#include <pthread.h>

WINDOW *ChatWindow, *LogWindow;

char* read_until(int fd, char end) {
    int i = 0, size;
    char c = '\0';
    char* string = (char*)malloc(sizeof(char));

    while (1) {
        size = read(fd, &c, sizeof(char));
        if (c != end && size > 0) {
            string = (char*)realloc(string, sizeof(char) * (i + 2));
            string[i++] = c;
        } else {
            break;
        }
    }
    string[i] = '\0';
    return string;
}

void endSignal(int signum) {
	// End ncurses
	delwin(ChatWindow);
	delwin(LogWindow);
	endwin();
	// End program
	exit(0);
}

void *updateThread(void *arg) {
	CLIENT *clnt;
	char *getmessage_1_arg;
	char **result;

	while(1){
		#ifndef	DEBUG
			clnt = clnt_create ("localhost", PROGRAM, VERSION, "udp");
			if (clnt == NULL) {
				clnt_pcreateerror ("localhost");
				exit (1);
			}
		#endif	/* DEBUG */

		result = getchat_1((void*)&getmessage_1_arg, clnt);
		if (result == (char **) NULL) {
			clnt_perror (clnt, "call failed");
		}

		#ifndef	DEBUG
			clnt_destroy (clnt);
		#endif	 /* DEBUG */

		wclear(LogWindow);
		char *temp = (char *)malloc(sizeof(char)*strlen(result[0]) + 2);
		sprintf(temp, "%s\n", result[0]);
		wprintw(LogWindow, temp);
		wscrl(LogWindow, 1);
		wrefresh(LogWindow);

		// Espera de 1 segon
		sleep(1);
	}
	return NULL;
}

void program_1(char *host) {
	CLIENT *clnt;
	char * *result_1;
	char *writeMsg_1_arg;

	writeMsg_1_arg = (char *) malloc(sizeof(char)*150);
	bzero(writeMsg_1_arg, 150);
	wclear(ChatWindow);
	wrefresh(ChatWindow);
	wprintw(ChatWindow, "Missatge: ");
	wrefresh(ChatWindow);
	wgetstr(ChatWindow, writeMsg_1_arg);
	wrefresh(ChatWindow);
	char * auxiliar = (char *) malloc(sizeof(char)*200);
	bzero(auxiliar, 200);
	sprintf(auxiliar, "-> %s: %s", host, writeMsg_1_arg);

	#ifndef	DEBUG
		clnt = clnt_create ("localhost", PROGRAM, VERSION, "udp");
		if (clnt == NULL) {
			clnt_pcreateerror ("localhost");
			exit (1);
		}
	#endif	/* DEBUG */

	result_1 = writemsg_1(&auxiliar, clnt);
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}

	#ifndef	DEBUG
		clnt_destroy (clnt);
	#endif	 /* DEBUG */
}

int main (int argc, char *argv[]) {
	char *host;
	pthread_t thread;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	// Signal init
	signal(SIGINT, endSignal);

	// Ncurses init
	initscr();
	LogWindow = newwin(20, 50, 0, 0);
	ChatWindow = newwin(5, 50, 21, 0);
	scrollok(LogWindow, TRUE);

	// Thread init
	pthread_create(&thread, NULL, updateThread, NULL);

	// Main program init
	while (1) {
		program_1 (host);
	}

	exit (0);
}
