/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "S4.h"
#include <ncurses.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <strings.h>
#include <pthread.h>

#define FILE_ERROR "Error en obrir el fitxer"

char* read_until(int fd, char end) {
	int i = 0, size;
	char c = '\0';
	char* string = (char*)malloc(sizeof(char));

	while (1) {
		size = read(fd, &c, sizeof(char));
		if (c != end && size > 0) {
			string = (char*)realloc(string, sizeof(char) * (i + 2));
			string[i++] = c;
		} else {
			break;
		}
	}

	string[i] = '\0';
	return string;
}

char ** getchat_1_svc(void *argp, struct svc_req *rqstp) {
	static char * result;
	int flag = 0;
	int fd = open("chat.txt", O_RDONLY);

	while (1) {
		char *readTxt = read_until(fd, '\n');
		if (readTxt[0] == '\0') break;
		if(flag == 0) {
			result = (char*)malloc(sizeof(char) * (strlen(readTxt) + 1));
			strcpy(result, readTxt);
			flag++;
		} else {
			result = (char*)realloc(result, sizeof(char) * (strlen(result) + strlen(readTxt) + 2));
			strcat(result, readTxt);
		}
		strcat(result, "\n");
	}

	return &result;
}

void * writemsg_1_svc(char **argp, struct svc_req *rqstp) {
	static char * result;

	int	fd = open ("chat.txt", O_APPEND | O_WRONLY);
	if (fd < 0) {
      printf(FILE_ERROR);
	    return NULL;
	}

	write(fd, argp[0], strlen(argp[0]));
	write(fd, "\n", 1);

	close(fd);

	return (void *) &result;
}
